### ISSUE TITLE
Error in init.cpp

### ISSUE THREAD

**Issue by azilber** [TeslacoinFoundation/Teslacoin-v.4.0#10]
There's a C++ error in init.cpp that prevents compilation:

```
init.cpp: In function ‘bool AppInit2()’:
init.cpp:704:88: error: cannot pass objects of non-trivially-copyable type ‘std::string {aka class std::basic_string<char>}’ through ‘...’
             fprintf(stderr, _("Error loading %s: Wallet corrupted").c_str(), walletFile);
```

This is resolved with PR: (https://github.com/TeslacoinFoundation/Teslacoin-v.4.0/pull/9)

Additionally scrypt-x86 and scrypt-x86_64 were missing, these were re-added from v3.4

**Comment by TeslacoinFoundation** [comment]
PR merged! Thanks for contributing! :)
